class person{
    constructor(name,age,gender,dob,location){
        this.name=name;
        this.age=age;
        this.gender=gender;
        this.dob=dob;
        this.location=location; 
    }
}
var person1 =new person("Gaya3","21","Female","14-05-2002","Tuticorin");
var person2 =new person("Latha","45","Female","20-06-1972","London");
var person3 =new person("Alana","21","Female","24-12-2002","Virudhunagar");

console.log(person1);
console.log(person2);
console.log(person3);